<?php
    require 'fpdf/fpdf.php';
    session_start();
    if(!isset($_SESSION['id'])){
        header("Location: ../admin/cerrarsesion.php");
    }

    // Configuración de la conexión a la base de datos (reemplaza con tus propios datos)
    $codigoInscripcion = isset($_GET['codigo_inscripcion']) ? $_GET['codigo_inscripcion'] : '';
    // Verifica que el código de inscripción no esté vacío
    if (empty($codigoInscripcion)) {
        die("Error: Código de inscripción no válido.");
    }

    class PDF extends FPDF{
        function titulo($texto){
            $this->Ln(5);
            $this->SetFont('Arial', 'B', '15');
            $this->Cell(0, 5, utf8_decode($texto), 0, 1, 'C');
            $this->Ln(5);
            $this->SetFont('Arial', '', 7);
        }

        function resultado($texto){
            $this->SetFont('Arial', 'B', 7);
            $this->Write(5, utf8_decode(strtoupper($texto)));
            $this->SetFont('Arial', '', 7);
        }
        function Header(){
            $imagen1 = "./ministerio1.png";
            $imagen2 = "./oficial.png";
            $imagen3 = "./logoprees.png";
            $this->Image($imagen1, 10, -2, 40);
            $this->Image($imagen2, 95, 5, 25);
            $this->Image($imagen3, 170, 5, 35);
            $this->SetFont('Times', '', 10);
            $this->Ln(20);
            $this->Cell(0, 5, utf8_decode('REPÚBLICA BOLIVARIANA DE VENEZUELA'), 0, 1, 'C');
            $this->Cell(0, 5, utf8_decode('MINISTERIO DEL PODER POPULAR PARA LA EDUCACION'), 0, 1, 'C');
            $this->Cell(0, 5, utf8_decode('C.E.I. SIMONCITO CONGRESO DE ANGOSTURA'), 0, 1, 'C');
            $this->Cell(0, 5, utf8_decode('SAN CRISTÓBAL ESTADO TÁCHIRA'), 0, 1, 'C');
            $this->Cell(0, 5, utf8_decode('CODIGO DE DEPENDENCIA 004102223'), 0, 1, 'C');
            $this->Cell(0, 5, utf8_decode('CODIGO DEA OD01252023'), 0, 1, 'C');
            $this->Ln(5);
            $this->SetFont('Arial', 'B', '20');
            $this->Cell(0, 5, utf8_decode("FICHA DE INSCRIPCIÓN"), 0, 1, 'C');
            $this->SetFontSize(15);
            $this->Ln(3);
            $this->Cell(0, 5, utf8_decode("AÑO ESCOLAR 2023-2024"), 0, 1, 'C');
            
        }

        function chart($y1, $y2){
            $this->Line(200, $y1, 200, $y2);
            $this->Line(170, $y1, 170, $y2);
            $this->Line(170, $y1, 200, $y1);
            $this->Line(170, $y2, 200, $y2);
        }
        function marcarX($x, $y){
            $this->SetFont('Arial', 'B', 7);
            $this->Text($x, $y-1, "X");
            $this->SetFont('Arial', '', 7);
        }
        function body($datos){
            
            //Datos ninos
            $interlineado = 5;
            $apellidosN = $datos['apellidos_b'];
            $nombresN = $datos['nombres_b'];
            $fnaN = date("d/m/Y", strtotime($datos['fna_b']));
            $edadN = $datos['edad_b'];
            $lnaN = $datos['lna_b'];
            $estadoN = $datos['estado_b'];
            $nacionalidadN = "por hacer";
            $cedulaN = $datos['cedula_estudiante'];
            $apellidosR = $datos['apellidos_r'];
            $nombresR = $datos['nombres_r'];
            $cedulaR = $datos['cedula_r'];
            $telefonoR = $datos['telefono_r'];
            $parentescoR = $datos['parentesco_r'];
            $apellidosM = $datos['apellidos_m'];
            $nombresM = $datos['nombres_m'];
            $cedulaM = $datos['cedula_m'];
            $telefonoM = $datos['telefono_m'];
            $estadoM = "por hacer";
            $nacionalidadM = "por hacer";
            $edadM = $datos['edad_m'];
            $correoM = $datos['correo_m'];
            $direccionMT = $datos['dt_m'];
            $telefonoMT = $datos['tt_m'];
            $telefonoMH = $datos['th_m'];
            $direccionMH = $datos['dh_m'];
            $educacionM = "por hacer";
            $ocupacionM = $datos['ocupacion_m'];
            $profesionM = $datos['profesion_m'];
            $datosExtraM = "Por hacer";
            $apellidosP = $datos['apellidos_pp'];
            $nombresP = $datos['nombres_pp'];
            $cedulaP = $datos['cedula_pp'];
            $telefonoP = $datos['telefono_pp'];
            $estadoP = "Por hacer";
            $nacionalidadP = "pOR HACER";
            $edadP = $datos['edad_pp'];
            $correoP = $datos['correo_pp'];
            $telefonoPT = $datos['tt_pp'];
            $direccionPT =$datos['dt_pp'];
            $telefonoPH = $datos['th_pp'];
            $direccionPH = $datos['dh_pp'];
            $educacionP = "Por hacer";
            $ocupacionP = $datos['ocupacion_pp'];
            $profesionP = $datos['profesion_pp'];
            $datosExtraP = "Por hacer";
            $enfermedad = "Asma";
            $motivoHospitalizacion = "aqui va el texto";
            $alergia = "NO tengo";
            $condicion = "Aun por verse";
            $esAtendido = "Si";
            $doctor = "Cesar Augusto Salvatierra";
            $autorizado = "Aqui iran los datos que voy a poner aca, aun por definir";
            $this->titulo('DATOS DEL NIÑO (A)');
            $this->Write(5, 'Apellidos: ');
            $this->resultado($apellidosN);
            $this->Line(22, $this->GetY()+4, 59, $this->GetY()+4);
            $this->SetX(63);
            $this->Write(5, 'Nombres: ');
            $this->Line(75, $this->GetY()+4, 128, $this->GetY()+4);
            $this->resultado($nombresN);
            $this->SetX(128);
            $this->Write(5, "Fecha de Nacimiento: ");
            $this->resultado($fnaN);
            $this->Line(154, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, "Edad: ");
            $this->resultado($edadN);
            $this->Line(18, $this->GetY()+4, 22, $this->GetY()+4);
            $this->chart(80, 115);
            $this->SetX(22);
            $this->Write(5, "Lugar de nacimiento: ");
            $this->resultado($lnaN);
            $this->Line(47, $this->GetY()+4, 89, $this->GetY()+4);
            $this->SetX(90);
            $this->Write(5, "Estado: ");
            $this->resultado($estadoN);
            $this->Line(100, $this->GetY()+4, 131, $this->GetY()+4);
            $this->SetX(132);
            $this->Write(5, "Nacionalidad: ");
            $this->resultado($nacionalidadN);
            $this->Line(149, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, "Procedencia: Hogar");
            $this->Line(33, $this->GetY()+4, 54, $this->GetY()+4);
            $this->marcarX(((33+54)/2)-1, $this->GetY()+4);
            $this->SetX(54);
            $this->Write(5, "Del mismo plantel");
            $this->Line(75, $this->GetY()+4, 98, $this->GetY()+4);
            $this->marcarX(((75+98)/2)-1, $this->GetY()+4);
            $this->SetX(98);
            $this->Write(5, "Otro plantel");
            $this->Line(112, $this->GetY()+4, 130, $this->GetY()+4);
            $this->marcarX(((112+130)/2)-1, $this->GetY()+4);
            $this->SetX(130);
            $this->Write(5, utf8_decode("Cédula escolar:"));
            $this->resultado($cedulaN);
            $this->Line(149, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("¿Tiene hermanos? Si:"));
            $this->Line(36, $this->GetY()+4, 46, $this->GetY()+4);
            $this->marcarX(((36+46)/2)-1, $this->GetY()+4);
            $this->SetX(45);
            $this->Write(5, "No:");
            $this->Line(51, $this->GetY()+4, 60, $this->GetY()+4);
            $this->marcarX(((51+60)/2)-1, $this->GetY()+4);
            $this->SetX(61);
            $this->Write(5, utf8_decode("¿Cuántos?"));
            $this->Line(74, $this->GetY()+4, 83, $this->GetY()+4);
            $this->marcarX(((74+83)/2)-1, $this->GetY()+4);
            $this->SetX(82);
            $this->Write(5, utf8_decode("V: "));
            $this->Line(86, $this->GetY()+4, 93, $this->GetY()+4);
            $this->marcarX(((86+93)/2)-1, $this->GetY()+4);
            $this->SetX(93);
            $this->Write(5, utf8_decode("H: "));
            $this->Line(97, $this->GetY()+4, 104, $this->GetY()+4);
            $this->marcarX(((97+104)/2)-1, $this->GetY()+4);
            $this->SetX(104);
            $this->Write(5, utf8_decode("Lugar entre hermanos: "));
            $this->Line(131, $this->GetY()+4, 166, $this->GetY()+4);
            $this->marcarX(((131+166)/2)-1, $this->GetY()+4);
            $this->Ln($interlineado*2);
            $this->SetFont('Arial', 'B', 8);
            $this->Line(11, $this->GetY()+4, 47, $this->GetY()+4);
            $this->Write(5, "Antecedentes Paranatales: ");
            $this->SetFont('Arial', '', 7);
            $this->Write(5, " Que enfermedad ha padecido: ");
            $this->resultado($enfermedad);
            $this->Line(83, $this->GetY()+4, 200, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode('¿Ha estado el niño(a) Hospitalizado?'));
            $this->SetX(51);
            $this->Write(5, utf8_decode("Si: "));
            $this->Line(55, $this->GetY()+4, 61, $this->GetY()+4);
            $this->marcarX(((55+61)/2)-1, $this->GetY()+4);
            $this->SetX(60);
            $this->Write(5, utf8_decode("No: "));
            $this->Line(65, $this->GetY()+4, 72, $this->GetY()+4);
            $this->marcarX(((65+72)/2)-1, $this->GetY()+4);
            $this->SetX(71);
            $this->Write(5, utf8_decode("¿Por qué?: "));
            $this->Line(85, $this->GetY()+4, 200, $this->GetY()+4);
            $this->resultado($motivoHospitalizacion);
            $this->Ln($interlineado);
            $this->Write(5, "¿Presenta alguna alergia a Medicamento, Polvo, Compuesto Alimenticio? Si:");
            $this->Line(97, $this->GetY()+4, 101, $this->GetY()+4);
            $this->marcarX(((97+101)/2)-1, $this->GetY()+4);
            $this->SetX(100);
            $this->Write(5, "No:");
            $this->Line(105, $this->GetY()+4, 109, $this->GetY()+4);
            $this->marcarX(((105+109)/2)-1, $this->GetY()+4);
            $this->SetX(109);
            $this->Write(5, utf8_decode("¿Cuál?: "));
            $this->Line(119, $this->GetY()+4, 200, $this->GetY()+4);
            $this->resultado($alergia);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("¿Padece alguna Condición?"));
            $this->SetX(42);
            $this->Write(5, "Si:");
            $this->Line(46, $this->GetY()+4, 50, $this->GetY()+4);
            $this->marcarX(((46+50)/2)-1, $this->GetY()+4);
            $this->SetX(50);
            $this->Write(5, "No:");
            $this->Line(54, $this->GetY()+4, 58, $this->GetY()+4);
            $this->marcarX(((54+58)/2)-1, $this->GetY()+4);
            $this->SetX(58);
            $this->Write(5, utf8_decode("¿Cuál?: "));
            $this->Line(68, $this->GetY()+4, 200, $this->GetY()+4);
            $this->resultado($condicion);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("¿Presentó Informe?"));
            $this->SetX(32);
            $this->Write(5, "Si:");
            $this->Line(37, $this->GetY()+4, 43, $this->GetY()+4);
            $this->marcarX(((37+43)/2)-1, $this->GetY()+4);
            $this->SetX(42);
            $this->Write(5, "No:      ;");
            $this->Line(47, $this->GetY()+4, 51, $this->GetY()+4);
            $this->marcarX(((47+51)/2)-1, $this->GetY()+4);
            $this->SetX(52);
            $this->Write(5, utf8_decode("¿Padece alguna limitación?"));
            $this->SetX(83);
            $this->Write(5, "Motora:");
            $this->Line(93, $this->GetY()+4, 97, $this->GetY()+4);
            $this->marcarX(((93+97)/2)-1, $this->GetY()+4);
            $this->SetX(96);
            $this->Write(5, "de Crecimiento:");
            $this->Line(115, $this->GetY()+4, 119, $this->GetY()+4);
            $this->marcarX(((115+119)/2)-1, $this->GetY()+4);
            $this->SetX(119);
            $this->Write(5, "Auditiva:");
            $this->Line(130, $this->GetY()+4, 134, $this->GetY()+4);
            $this->marcarX(((130+134)/2)-1, $this->GetY()+4);
            $this->SetX(134);
            $this->Write(5, "Visual:       ;");
            $this->Line(143, $this->GetY()+4, 147, $this->GetY()+4);
            $this->marcarX(((143+147)/2)-1, $this->GetY()+4);
            $this->SetX(148);
            $this->Write(5, utf8_decode("¿Es Atendido (a) por Especialista?: "));
            $this->Line(189, $this->GetY()+4, 200, $this->GetY()+4);
            $this->Write(5, $esAtendido);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode(" Datos del Dr. "));
            $this->Line(27, $this->GetY()+4, 144, $this->GetY()+4);
            $this->resultado($doctor);
            $this->SetX(144);
            $this->Write(5, utf8_decode("Tiende a enfermarse con facilidad"));
            $this->SetX(182);
            $this->Write(5, "Si");
            $this->Line(186, $this->GetY()+4, 190, $this->GetY()+4);
            $this->marcarX(((186+190)/2)-1, $this->GetY()+4);
            $this->SetX(190);
            $this->Write(5, "No");
            $this->Line(195, $this->GetY()+4, 199, $this->GetY()+4);
            $this->marcarX(((195+199)/2)-1, $this->GetY()+4);
            $this->Text(200, $this->GetY()+4, ".");
            $this->Ln($interlineado);

            //dATOS REPRESENTANTE
            $this->titulo("DATOS FAMILIARES");
            $this->resultado("Datos del Representante Legal:");
            $this->Line(11, $this->GetY()+4, 57, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, 'Apellidos: ');
            $this->resultado($apellidosR);
            $this->Line(22, $this->GetY()+4, 56, $this->GetY()+4);
            $this->SetX(57);
            $this->Write(5, 'Nombres: ');
            $this->resultado($nombresR);
            $this->Line(70, $this->GetY()+4, 109, $this->GetY()+4);
            $this->SetX(110);
            $this->Write(5, utf8_decode("Cédula: "));
            $this->resultado($cedulaR);
            $this->Line(120, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoR);
            $this->Line(145, $this->GetY()+4, 160, $this->GetY()+4);
            $this->SetX(160);
            $this->Write(5, "Parentezco: ");
            $this->resultado($parentescoR);
            $this->Line(175, $this->GetY()+4, 200, $this->GetY()+4);
            $this->Ln($interlineado*2);

            //mADRE
            //Cuadro madre
            $this->chart($this->GetY(), $this->GetY()+35);
            $this->resultado("Madre:");
            $this->Line(11, $this->GetY()+4, 20, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, 'Apellidos: ');
            $this->resultado($apellidosM);
            $this->Line(22, $this->GetY()+4, 56, $this->GetY()+4);
            $this->SetX(57);
            $this->Write(5, 'Nombres: ');
            $this->resultado($nombresM);
            $this->Line(70, $this->GetY()+4, 109, $this->GetY()+4);
            $this->SetX(110);
            $this->Write(5, utf8_decode("Cédula: "));
            $this->resultado($cedulaM);
            $this->Line(120, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoM);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Estado civil: "));
            $this->resultado($estadoM);
            $this->Line(25, $this->GetY()+4, 49, $this->GetY()+4);
            $this->SetX(50);
            $this->Write(5, "Nacionalidad: ");
            $this->resultado($nacionalidadM);
            $this->Line(67, $this->GetY()+4, 86, $this->GetY()+4);
            $this->SetX(87);
            $this->Write(5, "Edad: ");
            $this->resultado($edadM);
            $this->Line(95, $this->GetY()+4, 100, $this->GetY()+4);
            $this->SetX(100);
            $this->Write(5, "Correo: ");
            $this->resultado($correoM);
            $this->Line(110, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Dirección de Habitación: "));
            $this->resultado($direccionMH);
            $this->Line(39, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoMH);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Dirección de Trabajo: "));
            $this->resultado($direccionMT);
            $this->Line(35, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoMT);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Nivel académico: "));
            $this->resultado($educacionM);
            $this->Line(30, $this->GetY()+4, 60, $this->GetY()+4);
            $this->SetX(60);
            $this->Write(5, utf8_decode("Ocupación: "));
            $this->resultado($ocupacionM);
            $this->Line(74, $this->GetY()+4, 120, $this->GetY()+4);
            $this->SetX(120);
            $this->Write(5, utf8_decode("Profesión: "));
            $this->resultado($profesionM);
            $this->Line(133, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Otros datos de importancia sobre la situación familiar que se desee reflejar: "));
            $this->Line(94, $this->GetY()+$interlineado, 166, $this->GetY()+$interlineado);
            $this->resultado($datosExtraM);
            $this->Ln($interlineado);
            $this->Ln($interlineado);
            $this->Ln($interlineado);
            $this->Ln($interlineado);

            //PADRE
            //imagen padre
            $this->chart($this->GetY(), $this->GetY()+35);
            $this->resultado("Padre:");
            $this->Line(11, $this->GetY()+4, 20, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, 'Apellidos: ');
            $this->resultado($apellidosP);
            $this->Line(22, $this->GetY()+4, 56, $this->GetY()+4);
            $this->SetX(57);
            $this->Write(5, 'Nombres: ');
            $this->resultado($nombresP);
            $this->Line(70, $this->GetY()+4, 109, $this->GetY()+4);
            $this->SetX(110);
            $this->Write(5, utf8_decode("Cédula: "));
            $this->resultado($cedulaP);
            $this->Line(120, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoP);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Estado civil: "));
            $this->resultado($estadoP);
            $this->Line(25, $this->GetY()+4, 49, $this->GetY()+4);
            $this->SetX(50);
            $this->Write(5, "Nacionalidad: ");
            $this->resultado($nacionalidadP);
            $this->Line(67, $this->GetY()+4, 86, $this->GetY()+4);
            $this->SetX(87);
            $this->Write(5, "Edad: ");
            $this->resultado($edadP);
            $this->Line(95, $this->GetY()+4, 100, $this->GetY()+4);
            $this->SetX(100);
            $this->Write(5, "Correo: ");
            $this->resultado($correoP);
            $this->Line(110, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Dirección de Habitación: "));
            $this->resultado($direccionPH);
            $this->Line(39, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoPH);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Dirección de Trabajo: "));
            $this->resultado($direccionPT);
            $this->Line(35, $this->GetY()+4, 133, $this->GetY()+4);
            $this->SetX(133);
            $this->Write(5, utf8_decode("Teléfono: "));
            $this->resultado($telefonoPT);
            $this->Line(145, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Nivel académico: "));
            $this->resultado($educacionP);
            $this->Line(30, $this->GetY()+4, 60, $this->GetY()+4);
            $this->SetX(60);
            $this->Write(5, utf8_decode("Ocupación: "));
            $this->resultado($ocupacionP);
            $this->Line(74, $this->GetY()+4, 120, $this->GetY()+4);
            $this->SetX(120);
            $this->Write(5, utf8_decode("Profesión: "));
            $this->resultado($profesionP);
            $this->Line(133, $this->GetY()+4, 166, $this->GetY()+4);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Otros datos de importancia sobre la situación familiar que se desee reflejar: "));
            $this->Line(94, $this->GetY()+$interlineado, 166, $this->GetY()+$interlineado);
            $this->resultado($datosExtraP);
            $this->Ln($interlineado);
            $this->Ln($interlineado);
            $this->Ln($interlineado);
            $this->Write(5, utf8_decode("Persona autorizada para retirar el niño - niña de la Institución en Caso de Emergencias: "));
            $this->Line(11, $this->GetY()+4, 107, $this->GetY()+4);
            $this->resultado($autorizado);
            $this->Ln($interlineado*2);
            $this->SetFont('Arial', '', 6);
            $this->Write(5, utf8_decode("Anexar la copia de la Cédula."));
            $this->SetFont('Arial', '', 7);
        }
        function footer(){
            $this->SetY(-45);
            $this->SetX(100);
            $this->Write(5, "Directora (E)");
            $this->Line(90, $this->GetY(), 125, $this->GetY());
            $this->Ln(10);
            $this->Ln(10);
            $this->SetX(60);
            $this->Write(5, "Docente");
            $this->Line(48, $this->GetY(), 83, $this->GetY());
            $this->SetX(135);
            $this->Write(5, "Representante Legal");
            $this->Line(130, $this->GetY(), 165, $this->GetY());
            $this->Ln(10);
            include "./meses.php";
            $this->SetFont('Arial', '', 10);
            $this->SetY(-10);
            $this->SetX(-50);
            $this->Cell(0, 5, utf8_decode("Dia: ".date('d'). " Mes: ". date('m'). " Año: ". date('Y')));
        }
    }
    require 'conexion.php';
    $sql = "SELECT * FROM v_planillainscripcion
    WHERE codigo_inscripcion = '$codigoInscripcion';";
    $result = mysqli_query($conexion, $sql);
    $valores = mysqli_fetch_assoc($result);
    $pdf = new PDF('P', 'mm', 'Legal');
    $pdf->AddPage();
    $pdf->body($valores);
   

    $pdf->Output();
?> 